version: '3.8'

services:
  nextcloud_db:
    image: postgres:9.6.23-stretch
    container_name: nextcloud_db
    restart: always
    environment:
      - POSTGRES_DB_FILE=/run/secrets/nextcloud_db_name
      - POSTGRES_USER_FILE=/run/secrets/nextcloud_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nextcloud_db_password
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    secrets:
      - nextcloud_db_name
      - nextcloud_db_password
      - nextcloud_db_user

  nextcloud_app:
    image: linuxserver/nextcloud:php8-version-22.2.0
    container_name: nextcloud_app
    restart: always
    environment:
      - TZ=Europe/Rome
      - TRUSTED_PROXIES=nextcloud_proxy
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_TRUSTED_DOMAINS=domain.it
    volumes:
      - nextcloud_app_data:/data
      - nextcloud_app_log:/config/log
      - nextcloud_app_config:/config/www/nextcloud/config
      - nextcloud_app_apps:/config/www/nextcloud/apps
    depends_on:
      - nextcloud_db

  nextcloud_proxy:
    image: linuxserver/swag:version-1.20.0
    container_name: nextcloud_proxy
    restart: always
    ports:
      - 8085:80
      - 8086:443
    environment:
      - PUID=1050
      - PGID=1050
      - TZ=Europe/Rome
      - EMAIL=mail@domain.it
      - URL=domain.it
      - ONLY_SUBDOMAINS=false
      - VALIDATION=http
      - DNSPLUGIN=cloudflare
    volumes:
      - nextcloud_proxy:/config
      - nginx.cfg:/config/nginx/site-confs/default:ro

secrets:
  nextcloud_db_name:
    file: ./postgres_db.txt
  nextcloud_db_password:
    file: ./postgres_password.txt
  nextcloud_db_user:
    file: ./postgres_user.txt

volumes:
  nextcloud_db:
  nextcloud_app_data:
  nextcloud_app_log:
  nextcloud_app_config:
  nextcloud_app_apps:
  nextcloud_proxy:
